# Use official Node LTS image
FROM node:16-alpine as builder

WORKDIR /app
COPY frontend/package.json frontend/yarn.lock ./
RUN yarn install

COPY frontend ./
RUN yarn build

# Production stage
FROM nginx:alpine
COPY --from=builder /app/out /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
